---
title: "San Juan Chinook data compilation (DRAFT)"
author: "South Coast StA"
date: 'Last update: `r format(Sys.time(), sep="_", "%Y-%m-%d %H:%M")`'
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
    toc_collapsed: false 
    toc_depth: 5
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, warning=F, message=F)

library(here)
library(tidyverse)
library(readxl)
library(kableExtra)
library(bookdown)  
library(scales)       # for label_percent()
library(ggpubr)       # for ggarrange()
```

<br>

The focus of this data compendium is on Chinook, with non-chinook information included in the appendix. 

<br>

```{r child=here::here("scripts","markdown-overview", "part1-esc.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "part2-hatchery.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "part3-1-PACfisheries.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "part3-1-WCVIfisheries.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "part4-juvi.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "part4-1-marineJuvi.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "part5-enviro.Rmd")}

```

<br>

-----------------------------

<br>

```{r child=here::here("scripts","markdown-overview", "partx-others.Rmd")}

```

<br>







